language: ruby
rvm:
- 3.0.2

jobs:
include:
- os: linux
  arch: arm64
  env: OS=arm64_linux
- os: linux
  arch: amd64
  env: OS=amd64_linux
- os: windows
  arch: amd64
  env: OS=windows
- os: osx
  arch: amd64
  env: OS=osx
- os: linux
  arch: arm64
  env: OS=arm32_linux

script:
  - ruby -e "puts RUBY_PLATFORM"
